feat(contributions): add logic to handle and store a contribution val…
onlydustxyz/marketplace-backend pull request #105
Opened 2022-07-25 15:46 UTC by tdelabro

…idator

2022-07-25 15:51 UTC, tdelabro commented
I chose to have a nullable validator in DB, in order to be compliant with the contributions created before this update.

We can also choose to make it NON NULL and set the default value to "0x0" for the few that already exist. It will be more coherent with the future and simplify some parts of the code. I'm already doing this default thing, but on the fly at runtime instead of in the db.

wdyt?

2022-07-25 15:59 UTC, AnthonyBuisset commented
We are going to empty the DB one last time as we are deploying the proxy contract.
So we can have it NON NULL I guess

2022-07-25 16:04 UTC, Bernardstanislas requested changes

2022-07-25 16:04 UTC, Bernardstanislas commented on src/domain/entities/contribution.rs
> +use anyhow::anyhow;
I thought we removed it from domain?

2022-07-25 16:04 UTC, Bernardstanislas commented on src/domain/entities/contribution.rs
> +pub struct Filter {
Is it really business-related? I think it has been removed from @AnthonyBuisset refactor

2022-07-25 16:04 UTC, Bernardstanislas commented on src/infrastructure/database/project_repository.rs
> +				&contribution.validator.unwrap_or_else(|| "0x0".to_string()),
Agreed with @AnthonyBuisset , we can make it default in the DB, so that we remove this behaviour with a migration once the whole table has validators

2022-07-25 16:04 UTC, Bernardstanislas commented on src/routes/contributions.rs
> +pub struct CreateContributionBody {
`CreateContributionDto`

2022-07-25 16:04 UTC, Bernardstanislas commented on src/routes/contributions.rs
> +	let validator = FieldElement::from_str(&body.validator).map_err(|e| {
I know little about Rust, but can't this check be done somewhere inside the `CreateContributionDto` struct? It is an integrity check that should be held by the struct itself

2022-07-25 16:05 UTC, AnthonyBuisset commented on src/domain/entities/contribution.rs
> +pub type ValidatorAddress = FieldElement;
I think it is better to avoid talking about FieldElements as we decided (I think) that representation of addresses are going to be hexa strings

2022-07-25 16:11 UTC, tdelabro commented on src/domain/entities/contribution.rs
> +	type Err = anyhow::Error;
Hey it's because I just delete this file and moved the one that was under `types/` in place. There was code duplication.

2022-07-25 16:16 UTC, tdelabro commented on src/routes/contributions.rs
> +	let validator = FieldElement::from_str(&body.validator).map_err(|e| {
we probably can if we use some custom Deserialize implementation

2022-07-26 06:48 UTC, tdelabro commented on src/domain/entities/contribution.rs
> +use anyhow::anyhow;
removed

2022-07-26 06:48 UTC, tdelabro commented on src/domain/entities/contribution.rs
> +pub struct Filter {
removed

2022-07-26 06:50 UTC, tdelabro commented on src/infrastructure/database/project_repository.rs
> +				&contribution.validator.unwrap_or_else(|| "0x0".to_string()),
done

2022-07-26 06:51 UTC, tdelabro commented on src/routes/contributions.rs
> +pub struct CreateContributionBody {
done

2022-07-26 06:52 UTC, tdelabro commented on src/domain/entities/contribution.rs
> +	type Err = anyhow::Error;
fixed

2022-07-26 07:17 UTC, AnthonyBuisset commented on src/domain/entities/contribution.rs
> +pub type ValidatorAddress = FieldElement;
the fact that we have a felt is tightly coupled with our usage of Starknet
If we want to consider other ecosystems, we should not have this kind of coupling in the code.
But I guess it is easy enough to refactor later when the need comes

2022-07-26 07:19 UTC, Bernardstanislas commented on src/routes/contributions.rs
> +	let validator = FieldElement::from_str(&body.validator).map_err(|e| {
ok we'll do later then

2022-07-26 07:20 UTC, Bernardstanislas commented on src/domain/entities/contribution.rs
> +pub type ValidatorAddress = FieldElement;
Agreed with you @AnthonyBuisset, let's keep the `FieldElement` for now but we'll have to abstract it for further ecosystems integrations

2022-07-26 10:01 UTC, tdelabro commented on src/routes/contributions.rs
> +	let validator = FieldElement::from_str(&body.validator).map_err(|e| {
done, and tested

2022-07-26 10:22 UTC, Bernardstanislas approved these changes
Ok for me once the CI is green :)

2022-07-26 10:27 UTC, tekkac commented on src/infrastructure/database/contribution_repository.rs
> +			validator: contribution.validator.to_string(),
`to_string` isn't `0x` prefixed. It is stored as a decimal.

2022-07-26 10:28 UTC, AnthonyBuisset approved these changes

2022-07-26 10:34 UTC, tdelabro commented on src/infrastructure/database/contribution_repository.rs
> +			validator: contribution.validator.to_string(),
fixed

2022-07-26 14:09 UTC, merged