feat: add accept_application route and usecase
onlydustxyz/marketplace-backend pull request #135
Opened 2022-08-05 15:35 UTC by tdelabro

2022-08-05 17:43 UTC, Bernardstanislas requested changes

2022-08-05 17:43 UTC, Bernardstanislas commented on src/domain/repositories/application.rs
> +	fn accept_application(&self, id: &ApplicationId) -> Result<Application, Error>;
This should not live in a repository, this is some business action. This should be in a `ApplicationService`, which does the action and then calls a `save` method on this repository.
Repositories are pure data access services, not business logic holders

2022-08-05 17:43 UTC, Bernardstanislas commented on src/routes/applications/accept/tests.rs
> +use super::accept_application;
❤️

2022-08-08 10:16 UTC, tdelabro commented on src/domain/repositories/application.rs
> +	fn accept_application(&self, id: &ApplicationId) -> Result<Application, Error>;
done

2022-08-08 14:11 UTC, tekkac commented on src/infrastructure/database/tests/application_repository.rs
> +fn id_must_be_unique() {
I am not sure but I recall we discussed that `contributor_id` can only apply once, but not sure if it is specified in this sprint or User Story

2022-08-08 14:11 UTC, tekkac commented on src/routes/applications/accept/mod.rs
> +	// return the hash of the on-chain transaction containing the call
I assume this is for another US?

2022-08-08 14:21 UTC, tdelabro commented on src/infrastructure/database/domain_implementations/application/service.rs
> +						.filter(applications::status.eq(Status::Pending)),
done

2022-08-08 14:25 UTC, tdelabro commented on src/bin/utils/mod.rs
> -		.find(|contribution| contribution["onchain_id"] == contribution_onchain_id.to_string())
fixed

2022-08-08 14:25 UTC, tdelabro commented on src/infrastructure/database/domain_implementations/application/repository.rs
> +		println!("kind: {:?}", error);
done

2022-08-08 14:40 UTC, tdelabro commented on src/infrastructure/database/tests/application_repository.rs
> +fn id_must_be_unique() {
tested in `cannot_apply_twice`

2022-08-08 14:40 UTC, tdelabro commented on src/routes/applications/accept/mod.rs
> +	// return the hash of the on-chain transaction containing the call
yup

2022-08-08 14:40 UTC, tdelabro commented on src/infrastructure/database/domain_implementations/application/service.rs
> +					Self::InvalidEntity(Box::new(error)),
thanks!

2022-08-08 15:32 UTC, merged