🎨 🐛 update application and contribution status when transaction is done
onlydustxyz/marketplace-backend pull request #165
Opened 2022-08-25 21:54 UTC by ofux

Introduce the new usecase `on_contribution_assigned`

end2end tests will be added in another PR

2022-08-25 22:33 UTC, Bernardstanislas requested changes
You should avoid having business logic anywhere else than in the domain.
Based on the comments I wrote below, I would even consider removing the trait `ApplicationService`, since the application is never the entrypoint but the contribution is, and code the business logic in the `ContributionService`

2022-08-25 22:33 UTC, Bernardstanislas commented on marketplace-core/src/application/contribution/on_contribution_assigned.rs
> +		contribution.status = ContributionStatus::Assigned;
All the logic in this usecase should be in the `ApplicationService`. This is not technical, this is a business rule, let's put it in the domain

2022-08-25 22:33 UTC, Bernardstanislas commented on marketplace-domain/src/services/application.rs
> +	fn accept_application(&self, application: Application) -> Result<(), Error>;
Why is it still abstract? This service can be fully implemented, it relies on the `ApplicationRepository` and the `ContributionRepository` and calls the `update` methods.
Here all the logic is either in the use case, or in the infrastructure. Shouldn't be there, it is domain logic. 
See this PR https://github.com/onlydustxyz/marketplace-backend/pull/148 to have an example.
Moreover, reading this former PR, I would consider the `accept_application` method as part of the `ContributionService` rather than having an `ApplicationService` which doesn't do much and is always related to a contribution.

2022-08-25 22:33 UTC, Bernardstanislas commented on marketplace-infrastructure/src/database/domain_implementations/application/service.rs
> +			.set(applications::status.eq(Status::Refused))
This is a consequence of having an anemic domain: very specific code in the infra layer, where it should only be an `update` method that updates the whole entity, it is not the role of the infra to know which part will get updated.
See https://github.com/onlydustxyz/marketplace-backend/blob/main/marketplace-infrastructure/src/database/domain_implementations/contribution.rs#L51

2022-08-26 06:53 UTC, AnthonyBuisset commented on marketplace-infrastructure/src/database/domain_implementations/application/service.rs
> +			// Set the chosen one to accepted
typo

2022-08-26 06:53 UTC, AnthonyBuisset commented on marketplace-domain/src/services/application.rs
> +	fn accept_application(&self, application: Application) -> Result<(), Error>;
Indeed, in Rust we can set a default implementation that could still be overridden for mocks.
Agreed to have this in the ContributionService instead, makes more sense

2022-08-26 06:53 UTC, AnthonyBuisset commented on marketplace-domain/src/services/application.rs
> +#[automock]
can you please add automock in test only ? I will soon refactor the code base to have this new convention everywhere

2022-08-26 06:53 UTC, AnthonyBuisset commented on marketplace-core/src/application/contribution/on_contribution_assigned.rs
> +			.returning(move |_| Ok(Some(returned_contribution.to_owned())));
why do you need to call `to_owned` several times ?

2022-08-26 08:10 UTC, ofux commented on marketplace-domain/src/services/application.rs
> +#[automock]
Seen with @AnthonyBuisset : will be done in a next refactoring

2022-08-26 08:20 UTC, ofux commented on marketplace-domain/src/services/application.rs
> +	fn accept_application(&self, application: Application) -> Result<(), Error>;
I 100% agree with you. Currently, the repository literally implements the ApplicationService, which is a bad idea. However, I decided not to refactor this part in this PR as it would have needed at least 0.5 more days.
I suggest -as discussed with @AnthonyBuisset- that we do this refactoring in another Task.

2022-08-26 08:23 UTC, ofux commented on marketplace-infrastructure/src/database/domain_implementations/application/service.rs
> +			.set(applications::status.eq(Status::Refused))
Agreed, see my previous comment

2022-08-26 08:24 UTC, AnthonyBuisset approved these changes
As discussed together, we will pair parogram to finish the refactoring as it conflicts with my current tasks

2022-08-26 08:25 UTC, ofux commented on marketplace-core/src/application/contribution/on_contribution_assigned.rs
> +		contribution.status = ContributionStatus::Assigned;
Agreed. As discussed with @AnthonyBuisset we will merge it as-is and pair-program on the next Task to avoid too many conflicts.

2022-08-26 08:33 UTC, merged