refacotring proposal for aggregates management
onlydustxyz/marketplace-backend pull request #193
Opened 2022-09-05 06:59 UTC by AnthonyBuisset

* Differentiate Aggregate State from Aggregate behavior
* Make very clear that a Contribution is both a State and an Aggregate (see `type State = Self;`)
* Pass state as value in `apply()` so it cannot be used anymore and forces to be event sourced again

- :recycle: make Aggregate state immutable
- :recycle: pass events as reference in aggregate
- :recycle: remove event application from aggregate command as per SRP

2022-09-05 07:30 UTC, Bernardstanislas commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +	type State = Self;
I think we will do this for all aggregates, so do we even need this `State` type?
`apply_event` could take an immutable `&self` and return a new instance of `Self`, right? This would bring the immutability you are looking for, without the overhead of `State`

2022-09-05 07:37 UTC, AnthonyBuisset commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +	type State = Self;
yes we can, but I like how clear it is that we make the assumption of
```
type State = Self;
```
otherwise I feel we are mixing stuff

2022-09-05 08:08 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +	type State = Self;
I don't feel like we need this.
Self is already present and really expressive.
No need to complicate things with a ditto type

2022-09-06 07:57 UTC, tdelabro requested changes

2022-09-06 07:57 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +	#[fixture]
Tests in a separated file

2022-09-06 11:56 UTC, tdelabro commented on marketplace-core/src/application/contribution/apply.rs
> +		let contribution_id = contribution_id.to_owned();
Why do you have to own it?
You are using it as a reference on l73.

2022-09-06 11:57 UTC, tdelabro commented on marketplace-domain/src/aggregate.rs
> +	fn from_events(events: &Vec<Self::Event>) -> Self {
instead of `&Vec<Self::Event>` use `&[Self::Event]` for more versatile/generic code

2022-09-06 12:05 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
>  			return Err(Error::AlreadyApplied(contributor_id.to_owned()));
use `.clone()` when you want to clone to the same type.
`.to_owned()` is susceptible to change return a type which is not the one of you original value.

`to_owned` does more than `clone`. So if you just need to `clone` use `clone`

2022-09-06 12:09 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +				applicants: [&self.applicants[..], &[contributor_id.to_owned()]].concat(),
You are allocating a new vector there.
I think there is a way to move the original vector ownership from `self` to the new `Self` and then push the new applicant as it was done before.

This spare some allocation

2022-09-06 12:09 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
> +				applicants: [&self.applicants[..], &[contributor_id.to_owned()]].concat(),
It should be doable in two lines

2022-09-06 12:24 UTC, AnthonyBuisset commented on marketplace-domain/src/contribution/aggregate_root/mod.rs
>  			return Err(Error::AlreadyApplied(contributor_id.to_owned()));
if I have a reference (&) and I want to dereference (having the owned type) I have to call `to_owned` right ?
for instance in this particular case it is ok as the event owns the contributor_id which is passed by reference in the function.
Am I right ?

2022-09-06 15:03 UTC, tdelabro approved these changes

2022-09-06 15:03 UTC, merged