offchain signup
onlydustxyz/marketplace-backend pull request #242
Opened 2022-09-22 15:31 UTC by ofux

- ✨ introduce Contributor aggregate
- ✨ implement Contributor aggregate verify_github_association
- ✨ implement authenticate_user for Github Client
- ✨ implement AccountVerifier for Starknet
- ✨ add signup route
- ✨ update indexer to store contributor events
- ♻️ use traits to add convertion methods
- ♻️ update contributor projection to use contributor events
- ⚰️ remove dead code
- ✅ update refresh tests
- 🚨 fix clippy warnings
- ⚰️ remove signup crate

2022-09-22 15:47 UTC, Bernardstanislas approved these changes

2022-09-22 15:47 UTC, Bernardstanislas commented on marketplace-domain/src/contributor/aggregate/mod.rs
> +	pub async fn verify_github_association<V: OnChainAccountVerifier, G: GithubClient>(
❤️

2022-09-22 15:47 UTC, Bernardstanislas commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(event) =>
Don't you need to add a `#[case(selector::<contributor::GithubAccountAssociated>(), "GithubAccountAssociated")]` to actually reach this?

2022-09-22 15:56 UTC, ofux commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(event) =>
OMG yes, I actually even need to implement it ahaha :D
good catch!

2022-09-22 15:59 UTC, ofux commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(event) =>
wait, no, this event won't come from apibara actually.

2022-09-22 16:05 UTC, ofux commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(event) =>
here we go: https://github.com/onlydustxyz/marketplace-backend/pull/242/commits/ffbf407cd5f96f756cf01363315083c934ffd29b

2022-09-22 16:43 UTC, AnthonyBuisset approved these changes

2022-09-22 17:17 UTC, tdelabro requested changes

2022-09-22 17:17 UTC, tdelabro commented on marketplace-core/src/routes/dto/hex_prefixed_string.rs
> +}
you should use the TryInto trait instead there: https://doc.rust-lang.org/std/convert/trait.TryInto.html

2022-09-22 17:17 UTC, tdelabro commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +		if self.contributor_projection_repository.find_by_id(&contributor_id).is_err() {
This can be done in one DB action. With an insert _on_conflict_do_nothing

2022-09-22 17:17 UTC, tdelabro commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +			Event::Project(_) | Event::Contribution(_) => return,
Is there absolutely no way to Assign a contribution to a contributor_id that has not been GitHub associated before?

2022-09-22 17:17 UTC, tdelabro commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(_) => unimplemented!(), // Off chain events
`unimplemented!` cant take a message as argument. It will be better there than as a comment aside

2022-09-22 17:17 UTC, tdelabro commented on marketplace-infrastructure/src/database/schema.rs
> +        logo_url -> Nullable<Varchar>,
You should probably `cargo +nightly fmt`.

2022-09-23 14:37 UTC, ofux commented on marketplace-core/src/routes/dto/hex_prefixed_string.rs
> +}
I tried but can't because HexPrefixedString is defined in another crate

2022-09-23 14:39 UTC, ofux commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +		if self.contributor_projection_repository.find_by_id(&contributor_id).is_err() {
this is not equivalent: the check here allows me to avoid a useless call to github if the contributor already exists

2022-09-23 14:40 UTC, ofux commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +			Event::Project(_) | Event::Contribution(_) => return,
not currently. We'll be manageable once we get rid of the contributor_id I guess... but this is for another future PR :)

2022-09-23 14:42 UTC, ofux commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +			DomainEvent::Contributor(_) => unimplemented!(), // Off chain events
done

2022-09-23 14:42 UTC, ofux commented on marketplace-infrastructure/src/database/schema.rs
> +        logo_url -> Nullable<Varchar>,
I did. Also, the check doesn't fail. Not sure why

2022-09-23 15:11 UTC, AnthonyBuisset approved these changes
LGTM

2022-09-23 15:11 UTC, AnthonyBuisset commented on marketplace-domain/src/contributor/aggregate/mod.rs
> -		self,
the body was not using it anyway 👍

2022-09-23 15:11 UTC, AnthonyBuisset commented on migrations/2022-09-23-152506_add_github_account_associated_events/down.sql
> +DELETE FROM events WHERE aggregate_name = 'CONTRIBUTOR' AND "timestamp" = '2022-06-06 10:10:10.000';
🤣

2022-09-23 15:11 UTC, AnthonyBuisset commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> +						_ => unimplemented!("Off chain events"),
❤️

2022-09-23 15:34 UTC, ofux commented on marketplace-domain/src/contributor/aggregate/mod.rs
> -		self,
yes indeed!

2022-09-23 15:34 UTC, ofux commented on migrations/2022-09-23-152506_add_github_account_associated_events/down.sql
> +DELETE FROM events WHERE aggregate_name = 'CONTRIBUTOR' AND "timestamp" = '2022-06-06 10:10:10.000';
ahah yes, let's be cautious ;)

2022-09-26 08:15 UTC, tdelabro commented on marketplace-core/src/routes/dto/hex_prefixed_string.rs
> +}
So you should wrap HexContributorString in a new type and implement `From` on it

2022-09-26 08:15 UTC, tdelabro commented on marketplace-core/src/routes/dto/hex_prefixed_string.rs
> +}
Or make this implem part of the domain, when feature starknet is used

2022-09-26 08:16 UTC, tdelabro commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +			Event::Project(_) | Event::Contribution(_) => return,
ok

2022-09-26 08:16 UTC, tdelabro commented on marketplace-domain/src/contributor/projectors/contributor.rs
> +		if self.contributor_projection_repository.find_by_id(&contributor_id).is_err() {
ok

2022-09-26 08:17 UTC, tdelabro commented on marketplace-infrastructure/src/database/schema.rs
> +        logo_url -> Nullable<Varchar>,
ok

2022-09-26 08:19 UTC, ofux commented on marketplace-core/src/routes/dto/hex_prefixed_string.rs
> +}
This is what I did in the first time, but it looked overcomplicated compared to adding this trait.

2022-09-26 08:44 UTC, tdelabro approved these changes

2022-09-26 08:52 UTC, merged