Listen to contribution closed events
onlydustxyz/marketplace-backend pull request #276
Opened 2022-10-07 12:44 UTC by lechinoix

2022-10-10 07:16 UTC, AnthonyBuisset commented
Well done !
Could you please update the corresponding e2e test ?

2022-10-10 07:16 UTC, AnthonyBuisset approved these changes

2022-10-10 15:17 UTC, AnthonyBuisset approved these changes

2022-10-10 15:17 UTC, AnthonyBuisset commented on marketplace-domain/src/contribution/aggregate_root/event.rs
> +	// ! Deprecated, Use Closed event instead
should we migrate the events or keep this legacy in the code ?

2022-10-10 15:23 UTC, lechinoix commented on marketplace-domain/src/contribution/aggregate_root/event.rs
> +	// ! Deprecated, Use Closed event instead
Probably migrating would be better, we only have 3 events in production from this morning

2022-10-10 15:24 UTC, tdelabro submitted a review, later dismissed

2022-10-10 15:24 UTC, tdelabro commented on Makefile
> +setup:
You can probably store this indexer makefile somewhere else. Not at the root. 
Maybe under a indexer/ folder so we know what it is for

2022-10-10 15:24 UTC, tdelabro commented on marketplace-domain/src/contribution/aggregate_root/event.rs
> +	// ! Deprecated, Use Closed event instead
There is a rust attribute to do this:
https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute

2022-10-10 15:25 UTC, tdelabro commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/closed.rs
> +			0, 0, 12,
We talked this morning about having more realistic ids. Her its 0x12

2022-10-10 15:27 UTC, lechinoix commented on marketplace-domain/src/contribution/aggregate_root/event.rs
> +	// ! Deprecated, Use Closed event instead
I'm writing it right now

2022-10-10 15:27 UTC, tdelabro commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/mod.rs
>  pub use deleted::Deleted;
And remove the whole deleted event listening?
We can migrate events from Deleted to Closed, remove the `status` field, remove ContributionClosed from the codebase

2022-10-10 15:28 UTC, tdelabro commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> -	#[case(selector::<contribution::Deleted>(), "ContributionDeleted")]
If you keep the old event in place, you should as well keep it's tests

2022-10-10 15:29 UTC, tdelabro commented on marketplace-infrastructure/src/database/repositories/contribution.rs
> +		closed_: bool,
Why do you have to use `closed_` with underscore?
I don't see `closed` without underscore being used in this scope

2022-10-10 15:41 UTC, lechinoix commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/deleted.rs
>  	fn to_domain_event(mut topics: Topics) -> Result<Event, FromEventError> {
We want to keep retrocompatibility with on-chain delete events because they cannot be removed / migrated, we could also put the delete code in `closed.rs` but I think it would be a little confusing. Maybe a little comment at the top of the file to specify it shouldn't be used for new events ?

2022-10-10 15:41 UTC, lechinoix commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/mod.rs
>  pub use deleted::Deleted;
I believe we need to wait for the frontend to change before removing the status field itself, that's why they are temporarly both existing. For the migration I totally agree, I am currently writing the migration, but the on-chain events cannot be changed so I believe we need to keep at least the indexer part alive.

2022-10-10 15:41 UTC, lechinoix commented on migrations/2022-10-07-122521_add-closed-column-in-contributions/up.sql
> +ALTER TABLE contributions ADD closed BOOLEAN NOT NULL DEFAULT false;
Yeah does not cost anything, I wanted to do it with the contributions/refresh endpoint but way better with a migration

2022-10-10 16:12 UTC, AnthonyBuisset requested changes

2022-10-10 16:12 UTC, AnthonyBuisset commented on migrations/2022-10-10-152725_migrate-delete-events-to-close-events/down.sql
> +	events.payload -> 'Contribution' = 'Deleted'
I think you meant Closed

2022-10-10 16:38 UTC, lechinoix commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/closed.rs
> +			0, 0, 12,
I proposed an implementation but I have a warning that I do not understand, might be a good occasion to improve my rust skills :D

2022-10-10 16:38 UTC, lechinoix commented on migrations/2022-10-10-152725_migrate-delete-events-to-close-events/down.sql
> +	events.payload -> 'Contribution' = 'Deleted'
Thanks, corrected !

2022-10-10 16:38 UTC, lechinoix commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/mod.rs
> -	#[case(selector::<contribution::Deleted>(), "ContributionDeleted")]
Corrected

2022-10-10 16:51 UTC, lechinoix commented on marketplace-domain/src/contribution/aggregate_root/event.rs
> +	// ! Deprecated, Use Closed event instead
Done !

2022-10-10 16:52 UTC, lechinoix commented on Makefile
> +setup:
I removed (dumb) commands that were package specific, but I believe database connection and project setup are pretty global no ?

2022-10-11 08:12 UTC, lechinoix commented on marketplace-indexer/src/infrastructure/apibara/starknet/events/contribution/closed.rs
> +			0, 0, 12,
Alrighty seems to work now thx Tdelabro !

2022-10-11 09:57 UTC, AnthonyBuisset approved these changes

2022-10-11 13:22 UTC, merged