merge payment request and receipt in same aggregate
onlydustxyz/marketplace-backend pull request #362
Opened 2022-11-24 16:00 UTC by AnthonyBuisset

- 🔥 payment request is no longer event sourcable
- ♻️ move payment_request::create into payment::request
- ♻️ move payment::create to payment::process
- ⚰️ remove legacy payment_request aggregate

2022-11-24 17:03 UTC, ofux approved these changes
LGTM, we just need a few more checks I think

2022-11-24 17:03 UTC, ofux commented on domain/src/payment/aggregate.rs
> +	pub async fn request(
I think we should also check that the payment doesn't already exist here, as a payment cannot be requested it is was already processed for example.

2022-11-24 17:03 UTC, ofux commented on domain/src/payment/aggregate.rs
> +	pub fn add_receipt(
Check the payment exists (ie. was requested)?

2022-11-24 18:35 UTC, Bernardstanislas requested changes
I have the feeling you missed the part where you have to store the receipts inside the payment aggregate root? And do the business checks on it

2022-11-24 18:35 UTC, Bernardstanislas commented on api/src/application/payment/request.rs
> +		Payment::request(
Crystal clear

2022-11-24 18:35 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
> +	pub fn add_receipt(
Cannot be called if not event-sourced, so this check is already done

2022-11-24 18:35 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
>  		id: PaymentId,
You don't need the id since it's the aggregate you are calling the method on

2022-11-24 18:35 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
> +			PaymentEvent::Processed { id, .. } => Self { id: *id },
This should not create an aggregate instance, it should push in a private field a new payment receipt

2022-11-24 18:35 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
>  		id: PaymentId,
You should have `&self` though

2022-11-24 18:35 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
> +		let events = vec![PaymentEvent::Processed {
You should do the monetary checks here, see if the receipt does not exceed the initial amount requested + the already received receipt amounts

2022-11-24 18:36 UTC, Bernardstanislas requested changes

2022-11-24 18:36 UTC, Bernardstanislas commented on api/src/application/payment/process.rs
> +		let events: Vec<_> = Payment::add_receipt(payment_id, receipt_id.into(), amount, receipt)?
Fetch the payment first, then call `add_receipt` on it. This method should not be static

2022-11-24 19:57 UTC, AnthonyBuisset commented on domain/src/payment/aggregate.rs
> +	pub async fn request(
Yes indeed, planned for a next PR, I wanted to keep this one iso-functional

2022-11-24 19:58 UTC, AnthonyBuisset commented on domain/src/payment/aggregate.rs
>  		id: PaymentId,
Yes indeed, but I planned to add it in another PR along with the amount check

2022-11-25 07:45 UTC, Bernardstanislas commented on api/src/application/payment/process.rs
> +		let events: Vec<_> = Payment::add_receipt(payment_id, receipt_id.into(), amount, receipt)?
Seen IRL, you do it in the next PR

2022-11-25 07:59 UTC, AnthonyBuisset commented on api/src/application/payment/process.rs
> +		let events: Vec<_> = Payment::add_receipt(payment_id, receipt_id.into(), amount, receipt)?
I have updated the PR, new commits include this change

2022-11-25 09:46 UTC, Bernardstanislas commented on api/src/application/payment/process.rs
> +		let events: Vec<_> = Payment::add_receipt(payment_id, receipt_id.into(), amount, receipt)?
ok I'm reviewing it

2022-11-25 09:49 UTC, Bernardstanislas approved these changes

2022-11-25 09:49 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
> +	requested_usd_amount: Decimal,
Oh even simpler than what I had in mind with the vec of payments, great!

2022-11-25 09:49 UTC, Bernardstanislas commented on domain/src/payment/aggregate.rs
> +		println!("paid_usd_amount: {}", self.paid_usd_amount);
Put some traces maybe?

2022-11-25 10:36 UTC, AnthonyBuisset commented on domain/src/payment/aggregate.rs
> +		println!("paid_usd_amount: {}", self.paid_usd_amount);
indeed ! leftover of debugging, will add a nice trace instead 👍

2022-11-25 11:57 UTC, merged